modLoader = "javafml"
loaderVersion = "[1,)"
license = "ARR"
issueTrackerURL = "https://modrinth.com/project/editvillagers-mod"

[[mods]]
modId = "${id}"
version = "${version}"
displayName = "${name}"
authors = "Eeqzy"
description = "Create a villager through the GUI in just a couple of clicks!"
logoFile = "assets/editvillager/icon.png"

[[dependencies.${id}]]
modId = "neoforge"
type = "required"
versionRange = "[21,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.${id}]]
modId = "minecraft"
type = "required"
versionRange = "[26.1,26.2)"
ordering = "NONE"
side = "BOTH"

[[dependencies.${id}]]
modId = "architectury"
type = "required"
versionRange = "[13.0.0,)"
ordering = "AFTER"
side = "BOTH"

[[mixins]]
config = "editvillager.mixins.json"
