org.gradle.jvmargs=-Xmx4G
org.gradle.parallel=true
org.gradle.configuration-cache=false
systemProp.org.gradle.internal.http.connectionTimeout=120000
systemProp.org.gradle.internal.http.socketTimeout=120000

mod.version=1.2.0
mod.group=lv.editvillager
mod.id=editvillager
mod.name=EditVillager
archives_base_name=EditVillagers-1.2.0

dev.kikugie.stonecutter.hard_mode=true
